---
grails:
    profile: web-plugin
    codegen:
        defaultPackage: images.client.plugin
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
